---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpjs
  namespace: production
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: httpjs
    spec:
      containers:
      - name: httpjs
        image: eu.gcr.io/turnkey-cocoa-720/httpjs:1.0.2
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 300Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: httpjs
          mountPath: "/usr/src/httpjs/etc/certs"
          readOnly: true
      volumes:
      - name: httpjs
        secret:
          secretName: httpjs
